<?xml version="1.0" encoding="utf-8"?><Database Name="Parcial_1" Class="SQLBaseLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=XAVIER-JR\SQLEXPRESS;Initial Catalog=Parcial_1;Integrated Security=True" SettingsObjectName="Capa_Datos.Properties.Settings" SettingsPropertyName="Parcial_1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_Productos" Member="Tbl_Productos">
    <Type Name="Tbl_Productos">
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pro_cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pro_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pro_prov" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_Proveedor_Tbl_Productos" Member="Tbl_Proveedor" ThisKey="pro_prov" OtherKey="prov_id" Type="Tbl_Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Proveedor" Member="Tbl_Proveedor">
    <Type Name="Tbl_Proveedor">
      <Column Name="prov_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prov_nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="prov_estado" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_Proveedor_Tbl_Productos" Member="Tbl_Productos" ThisKey="prov_id" OtherKey="pro_prov" Type="Tbl_Productos" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_TipoUsuario" Member="Tbl_TipoUsuario">
    <Type Name="Tbl_TipoUsuario">
      <Column Name="tipo_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tipo_nombre" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_estado" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_TipoUsuario_Tbl_Usuario" Member="Tbl_Usuario" ThisKey="tipo_id" OtherKey="usu_tipo" Type="Tbl_Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Usuario" Member="Tbl_Usuario">
    <Type Name="Tbl_Usuario">
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_nombre" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usu_apellido" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usu_cedula" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usu_direrccion" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="usu_estado" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="usu_nomLogin" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usu_correo" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="usu_tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usu_fechacreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="usu_contraLogin" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Tbl_TipoUsuario_Tbl_Usuario" Member="Tbl_TipoUsuario" ThisKey="usu_tipo" OtherKey="tipo_id" Type="Tbl_TipoUsuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>